# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.analog_list_v2 import AnalogListV2  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalogListV2(unittest.TestCase):
    """AnalogListV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalogListV2(self):
        """Test AnalogListV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.analog_list_v2.AnalogListV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
