# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.analog_list_api import AnalogListApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalogListApi(unittest.TestCase):
    """AnalogListApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.analog_list_api.AnalogListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analog_list_get(self):
        """Test case for analog_list_get

        Получить кроссы  # noqa: E501
        """
        pass

    def test_analog_list_post(self):
        """Test case for analog_list_post

        Добавить кроссы в общую базу  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
