# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_list_api import ProductListApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductListApi(unittest.TestCase):
    """ProductListApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.product_list_api.ProductListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_image_list_get(self):
        """Test case for image_list_get

        Получение картинки  # noqa: E501
        """
        pass

    def test_product_applicability_list_get(self):
        """Test case for product_applicability_list_get

        Применяемость детали к автомобилям  # noqa: E501
        """
        pass

    def test_product_list_get(self):
        """Test case for product_list_get

        Детали  # noqa: E501
        """
        pass

    def test_product_number_list_get(self):
        """Test case for product_number_list_get

        Получить список номеров  # noqa: E501
        """
        pass

    def test_product_parameter_list_get(self):
        """Test case for product_parameter_list_get

        Дополнительная информации о детали  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
