# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.manufacturer_list import ManufacturerList  # noqa: F401,E501
from swagger_client.models.model_list import ModelList  # noqa: F401,E501
from swagger_client.models.modification_list import ModificationList  # noqa: F401,E501


class CarListV2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'manufacturer_list': 'ManufacturerList',
        'model_list': 'ModelList',
        'modification_list': 'ModificationList'
    }

    attribute_map = {
        'manufacturer_list': 'manufacturerList',
        'model_list': 'modelList',
        'modification_list': 'modificationList'
    }

    def __init__(self, manufacturer_list=None, model_list=None, modification_list=None):  # noqa: E501
        """CarListV2 - a model defined in Swagger"""  # noqa: E501

        self._manufacturer_list = None
        self._model_list = None
        self._modification_list = None
        self.discriminator = None

        self.manufacturer_list = manufacturer_list
        self.model_list = model_list
        self.modification_list = modification_list

    @property
    def manufacturer_list(self):
        """Gets the manufacturer_list of this CarListV2.  # noqa: E501


        :return: The manufacturer_list of this CarListV2.  # noqa: E501
        :rtype: ManufacturerList
        """
        return self._manufacturer_list

    @manufacturer_list.setter
    def manufacturer_list(self, manufacturer_list):
        """Sets the manufacturer_list of this CarListV2.


        :param manufacturer_list: The manufacturer_list of this CarListV2.  # noqa: E501
        :type: ManufacturerList
        """
        if manufacturer_list is None:
            raise ValueError("Invalid value for `manufacturer_list`, must not be `None`")  # noqa: E501

        self._manufacturer_list = manufacturer_list

    @property
    def model_list(self):
        """Gets the model_list of this CarListV2.  # noqa: E501


        :return: The model_list of this CarListV2.  # noqa: E501
        :rtype: ModelList
        """
        return self._model_list

    @model_list.setter
    def model_list(self, model_list):
        """Sets the model_list of this CarListV2.


        :param model_list: The model_list of this CarListV2.  # noqa: E501
        :type: ModelList
        """
        if model_list is None:
            raise ValueError("Invalid value for `model_list`, must not be `None`")  # noqa: E501

        self._model_list = model_list

    @property
    def modification_list(self):
        """Gets the modification_list of this CarListV2.  # noqa: E501


        :return: The modification_list of this CarListV2.  # noqa: E501
        :rtype: ModificationList
        """
        return self._modification_list

    @modification_list.setter
    def modification_list(self, modification_list):
        """Sets the modification_list of this CarListV2.


        :param modification_list: The modification_list of this CarListV2.  # noqa: E501
        :type: ModificationList
        """
        if modification_list is None:
            raise ValueError("Invalid value for `modification_list`, must not be `None`")  # noqa: E501

        self._modification_list = modification_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CarListV2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CarListV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
