# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.manufacturer_list_row import ManufacturerListRow  # noqa: F401,E501


class ManufacturerList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mf': 'list[ManufacturerListRow]'
    }

    attribute_map = {
        'mf': 'mf'
    }

    def __init__(self, mf=None):  # noqa: E501
        """ManufacturerList - a model defined in Swagger"""  # noqa: E501

        self._mf = None
        self.discriminator = None

        self.mf = mf

    @property
    def mf(self):
        """Gets the mf of this ManufacturerList.  # noqa: E501


        :return: The mf of this ManufacturerList.  # noqa: E501
        :rtype: list[ManufacturerListRow]
        """
        return self._mf

    @mf.setter
    def mf(self, mf):
        """Sets the mf of this ManufacturerList.


        :param mf: The mf of this ManufacturerList.  # noqa: E501
        :type: list[ManufacturerListRow]
        """
        if mf is None:
            raise ValueError("Invalid value for `mf`, must not be `None`")  # noqa: E501

        self._mf = mf

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ManufacturerList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManufacturerList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
