# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.manufacturer_list_api import ManufacturerListApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManufacturerListApi(unittest.TestCase):
    """ManufacturerListApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.manufacturer_list_api.ManufacturerListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_manufacturer_list_get(self):
        """Test case for manufacturer_list_get

        Получение списка производителей  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
