# coding: utf-8

"""
    База кроссов автозапчастей FAPI. Описание доступа через API

    База кроссов автозапчастей FAPI. Описание доступа через API  # noqa: E501

    OpenAPI spec version: 1.0.3
    Contact: development.iisis@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.parameter_list_row import ParameterListRow  # noqa: E501
from swagger_client.rest import ApiException


class TestParameterListRow(unittest.TestCase):
    """ParameterListRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameterListRow(self):
        """Test ParameterListRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.parameter_list_row.ParameterListRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
